
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 16 23:10:56 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 52;
  public static final int LBRACKET = 45;
  public static final int CONST = 6;
  public static final int CASE = 20;
  public static final int NOT_EQUAL = 34;
  public static final int LPAREN = 43;
  public static final int SEMI = 39;
  public static final int GREATER = 35;
  public static final int CONTINUE = 16;
  public static final int NUM_CONST = 51;
  public static final int LESS = 37;
  public static final int FOR = 17;
  public static final int MINUS = 23;
  public static final int RPAREN = 44;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 30;
  public static final int DIV = 25;
  public static final int LESS_EQUAL = 38;
  public static final int PLUS = 22;
  public static final int ASSIGN = 29;
  public static final int IF = 11;
  public static final int CARET = 32;
  public static final int DOT = 42;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 46;
  public static final int EQUAL = 33;
  public static final int GREATER_EQUAL = 36;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 24;
  public static final int MOD = 26;
  public static final int IDENT = 50;
  public static final int BREAK = 9;
  public static final int VOID = 7;
  public static final int SWITCH = 19;
  public static final int COLON = 40;
  public static final int LBRACE = 47;
  public static final int ELSE = 10;
  public static final int ENUM = 3;
  public static final int READ = 14;
  public static final int DEFAULT = 21;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 8;
  public static final int BOOL_CONST = 53;
  public static final int QUESTION = 49;
  public static final int DEC = 31;
  public static final int PRINT = 13;
  public static final int LENGTH = 18;
}

