
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 12:54:17 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 53;
  public static final int LBRACKET = 46;
  public static final int CONST = 6;
  public static final int NOT_EQUAL = 35;
  public static final int CASE = 21;
  public static final int LPAREN = 44;
  public static final int SEMI = 40;
  public static final int GREATER = 36;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 52;
  public static final int LESS = 38;
  public static final int FOR = 18;
  public static final int MINUS = 24;
  public static final int RPAREN = 45;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int COMMA = 42;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIV = 26;
  public static final int LESS_EQUAL = 39;
  public static final int PLUS = 23;
  public static final int ASSIGN = 30;
  public static final int IF = 12;
  public static final int CARET = 33;
  public static final int DOT = 43;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int RBRACKET = 47;
  public static final int EQUAL = 34;
  public static final int GREATER_EQUAL = 37;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int MOD = 27;
  public static final int IDENT = 51;
  public static final int BREAK = 10;
  public static final int VOID = 7;
  public static final int SWITCH = 20;
  public static final int COLON = 41;
  public static final int LBRACE = 48;
  public static final int ELSE = 11;
  public static final int ENUM = 3;
  public static final int READ = 15;
  public static final int FINAL = 9;
  public static final int DEFAULT = 22;
  public static final int RBRACE = 49;
  public static final int EXTENDS = 8;
  public static final int BOOL_CONST = 54;
  public static final int QUESTION = 50;
  public static final int DEC = 32;
  public static final int PRINT = 14;
  public static final int LENGTH = 19;
}

