package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:
    boolean errorDetected = false;
    Logger log = Logger.getLogger(getClass());

    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
        done_parsing();
        report_error(message, info);
    }

    public void syntax_error(Symbol curr_token) {
        report_error("\nSintaksna greska", curr_token);
    }

    public void unrecovered_syntax_error(Symbol curr_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", curr_token);
    }

    public void report_error(String message, Object info) {
        errorDetected = true;
        StringBuilder msg = new StringBuilder(message);
        if (info instanceof Symbol) {
            msg.append(" na liniji ").append(((Symbol)info).left);
        }
        log.error(msg.toString());
    }
:}

scan with {:
    Symbol s = this.getScanner().next_token();
    if (s != null && s.value != null) {
        log.info(s.toString() + " " + s.value.toString());
    }
    return s;
:}

terminal PROGRAM, ENUM, CLASS, ABSTRACT, CONST, VOID, EXTENDS;
terminal BREAK, ELSE, IF, NEW, PRINT, READ, RETURN, CONTINUE, FOR, LENGTH, SWITCH, CASE;
terminal PLUS, MINUS, MUL, DIV, MOD, AND, OR, ASSIGN, INC, DEC;
terminal EQUAL, NOT_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL;
terminal SEMI, COLON, COMMA, DOT, LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, QUESTION;
terminal String IDENT;
terminal Integer NUM_CONST;
terminal Character CHAR_CONST;
terminal Boolean BOOL_CONST;

nonterminal Program Program;
nonterminal DeclarationList DeclarationList;
nonterminal GlobalVarDeclaration GlobalVarDeclaration;
nonterminal GlobalVarList GlobalVarList;
nonterminal GlobalVar GlobalVar;
nonterminal GlobalMethodDeclarationList GlobalMethodDeclarationList;
nonterminal GlobalMethodDeclaration GlobalMethodDeclaration;
nonterminal ConstDeclaration ConstDeclaration;
nonterminal VarDeclaration VarDeclaration;
nonterminal EnumDeclaration EnumDeclaration;
nonterminal ClassDeclaration ClassDeclaration;
nonterminal AbstractClassDeclaration AbstractClassDeclaration;
nonterminal ConstList ConstList;
nonterminal Const Const;
nonterminal VarList VarList;
nonterminal Var Var;
nonterminal EnumConstList EnumConstList;
nonterminal EnumConst EnumConst;
nonterminal MethodDeclarationList MethodDeclarationList;
nonterminal AbstractClassMethodDeclarationList AbstractClassMethodDeclarationList;
nonterminal VarDeclarationList VarDeclarationList;
nonterminal MethodDeclaration MethodDeclaration;
nonterminal AbstractMethodDeclaration AbstractMethodDeclaration;
nonterminal FormalParamsList FormalParamsList;
nonterminal FormalParam FormalParam;
nonterminal StatementList StatementList;
nonterminal Statement Statement;
nonterminal DesignatorStatement DesignatorStatement;
nonterminal CaseList CaseList;
nonterminal Case Case;
nonterminal ForInit ForInit;
nonterminal ForCond ForCond;
nonterminal ForAct ForAct;
nonterminal Else Else;
nonterminal Return Return;
nonterminal Condition Condition;
nonterminal ActualParamsList ActualParamsList;
nonterminal ConditionFactor ConditionFactor;
nonterminal ConditionTerm ConditionTerm;
nonterminal Sign Sign;
nonterminal SkipElse SkipElse;
nonterminal SkipTernary SkipTernary;
nonterminal ProgramName ProgramName;
nonterminal EnumName EnumName;
nonterminal RelOp RelOp;
nonterminal AddOp AddOp;
nonterminal MulOp MulOp;
nonterminal FieldDeclarationList FieldDeclarationList;
nonterminal FieldDeclaration FieldDeclaration;
nonterminal FieldList FieldList;
nonterminal Field Field;
nonterminal ForStart ForStart;
nonterminal CaseStart CaseStart;
nonterminal SwitchStart SwitchStart;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Term, TermList, Factor, FactorList, ArithmeticExpression, Expression;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Type, ClassName, AbstractClassName;
nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, MethodHeader, GlobalMethodHeader, FieldArrayName, EndArrayName;

precedence left ELSE;

Program ::= (Program) PROGRAM ProgramName:P1 DeclarationList:D2 LBRACE GlobalMethodDeclarationList:G3 RBRACE {: RESULT=new Program(P1, D2, G3); RESULT.setLine(P1left); :};
ProgramName ::= (ProgramName) IDENT:I1 {: RESULT=new ProgramName(I1); RESULT.setLine(I1left); :};
DeclarationList ::= (DeclarationListConst) DeclarationList:D1 ConstDeclaration:C2 {: RESULT=new DeclarationListConst(D1, C2); RESULT.setLine(D1left); :}
                    |
                    (DeclarationListVar) DeclarationList:D1 GlobalVarDeclaration:G2 {: RESULT=new DeclarationListVar(D1, G2); RESULT.setLine(D1left); :}
                    |
                    (DeclarationListClass) DeclarationList:D1 ClassDeclaration:C2 {: RESULT=new DeclarationListClass(D1, C2); RESULT.setLine(D1left); :}
                    |
                    (DeclarationListEnum) DeclarationList:D1 EnumDeclaration:E2 {: RESULT=new DeclarationListEnum(D1, E2); RESULT.setLine(D1left); :}
                    |
                    (DeclarationListAbstractClass) DeclarationList:D1 AbstractClassDeclaration:A2 {: RESULT=new DeclarationListAbstractClass(D1, A2); RESULT.setLine(D1left); :}
                    |
                    (DeclarationListEmpty) {: RESULT=new DeclarationListEmpty(); :} /* epsilon */
                    ;
ConstDeclaration ::= (ConstDeclaration) CONST Type:T1 ConstList:C2 SEMI {: RESULT=new ConstDeclaration(T1, C2); RESULT.setLine(T1left); :};
Type ::= (Type) IDENT:I1 {: RESULT=new Type(I1); RESULT.setLine(I1left); :};
ConstList ::= (ConstListMultiple) ConstList:C1 COMMA Const:C2 {: RESULT=new ConstListMultiple(C1, C2); RESULT.setLine(C1left); :}
              |
              (ConstListSingle) Const:C1 {: RESULT=new ConstListSingle(C1); RESULT.setLine(C1left); :}
              ;
Const ::= (ConstNum) IDENT:I1 ASSIGN NUM_CONST:N2 {: RESULT=new ConstNum(I1, N2); RESULT.setLine(I1left); :}
          |
          (ConstChar) IDENT:I1 ASSIGN CHAR_CONST:C2 {: RESULT=new ConstChar(I1, C2); RESULT.setLine(I1left); :}
          |
          (ConstBool) IDENT:I1 ASSIGN BOOL_CONST:B2 {: RESULT=new ConstBool(I1, B2); RESULT.setLine(I1left); :}
          ;
GlobalVarDeclaration ::= (GlobalVarDeclaration) Type:T1 GlobalVarList:G2 SEMI {: RESULT=new GlobalVarDeclaration(T1, G2); RESULT.setLine(T1left); :};
GlobalVarList ::= (GlobalVarListMultiple) GlobalVarList:G1 COMMA GlobalVar:G2 {: RESULT=new GlobalVarListMultiple(G1, G2); RESULT.setLine(G1left); :}
                  |
                  (GlobalVarListSingle) GlobalVar:G1 {: RESULT=new GlobalVarListSingle(G1); RESULT.setLine(G1left); :}
                  ;
GlobalVar ::= (GlobalVarSingle) IDENT:I1 {: RESULT=new GlobalVarSingle(I1); RESULT.setLine(I1left); :}
              |
              (GlobalVarArray) IDENT:I1 LBRACKET RBRACKET {: RESULT=new GlobalVarArray(I1); RESULT.setLine(I1left); :}
              ;
GlobalMethodDeclarationList ::= (GlobalMethodDeclarationListMore) GlobalMethodDeclarationList:G1 GlobalMethodDeclaration:G2 {: RESULT=new GlobalMethodDeclarationListMore(G1, G2); RESULT.setLine(G1left); :}
                                |
                                (GlobalMethodDeclarationListEmpty) {: RESULT=new GlobalMethodDeclarationListEmpty(); :} /* epsilon */
                                ;
GlobalMethodDeclaration ::= (GlobalMethodDeclarationParams) GlobalMethodHeader:G1 LPAREN FormalParamsList:F2 RPAREN VarDeclarationList:V3 LBRACE StatementList:S4 RBRACE {: RESULT=new GlobalMethodDeclarationParams(G1, F2, V3, S4); RESULT.setLine(G1left); :}
                            |
                            (GlobalMethodDeclarationNoParams) GlobalMethodHeader:G1 LPAREN RPAREN VarDeclarationList:V2 LBRACE StatementList:S3 RBRACE {: RESULT=new GlobalMethodDeclarationNoParams(G1, V2, S3); RESULT.setLine(G1left); :}
                            ;
GlobalMethodHeader ::= (GlobalMethodHeaderType) Type:T1 IDENT:I2 {: RESULT=new GlobalMethodHeaderType(T1, I2); RESULT.setLine(T1left); :}
                       |
                       (GlobalMethodHeaderVoid) VOID IDENT:I1 {: RESULT=new GlobalMethodHeaderVoid(I1); RESULT.setLine(I1left); :}
                       ;
EnumDeclaration ::= (EnumDeclaration) ENUM EnumName:E1 LBRACE EnumConstList:E2 RBRACE {: RESULT=new EnumDeclaration(E1, E2); RESULT.setLine(E1left); :};
EnumName ::= (EnumName) IDENT:I1 {: RESULT=new EnumName(I1); RESULT.setLine(I1left); :};
EnumConstList ::= (EnumConstListMultiple) EnumConstList:E1 COMMA EnumConst:E2 {: RESULT=new EnumConstListMultiple(E1, E2); RESULT.setLine(E1left); :}
                  |
                  (EnumConstListSingle) EnumConst:E1 {: RESULT=new EnumConstListSingle(E1); RESULT.setLine(E1left); :}
                  ;
EnumConst ::= (EnumConstNoAssign) IDENT:I1 {: RESULT=new EnumConstNoAssign(I1); RESULT.setLine(I1left); :}
              |
              (EnumConstAssign) IDENT:I1 ASSIGN NUM_CONST:N2 {: RESULT=new EnumConstAssign(I1, N2); RESULT.setLine(I1left); :}
              ;
ClassDeclaration ::= (ClassDeclarationMethodList) CLASS ClassName:C1 LBRACE FieldDeclarationList:F2 LBRACE MethodDeclarationList:M3 RBRACE RBRACE {: RESULT=new ClassDeclarationMethodList(C1, F2, M3); RESULT.setLine(C1left); :}
                     |
                     (ClassDeclarationNoMethodList) CLASS ClassName:C1 LBRACE FieldDeclarationList:F2 RBRACE {: RESULT=new ClassDeclarationNoMethodList(C1, F2); RESULT.setLine(C1left); :}
                     ;
AbstractClassDeclaration ::= (AbstractClassDeclarationMethodList) ABSTRACT CLASS AbstractClassName:A1 LBRACE FieldDeclarationList:F2 LBRACE AbstractClassMethodDeclarationList:A3 RBRACE RBRACE {: RESULT=new AbstractClassDeclarationMethodList(A1, F2, A3); RESULT.setLine(A1left); :}
                             |
                             (AbstractClassDeclarationNoMethodList) ABSTRACT CLASS AbstractClassName:A1 LBRACE FieldDeclarationList:F2 RBRACE {: RESULT=new AbstractClassDeclarationNoMethodList(A1, F2); RESULT.setLine(A1left); :}
                             ;
ClassName ::= (ClassNameNoExtends) IDENT:I1 {: RESULT=new ClassNameNoExtends(I1); RESULT.setLine(I1left); :}
              |
              (ClassNameExtends) IDENT:I1 EXTENDS Type:T2 {: RESULT=new ClassNameExtends(I1, T2); RESULT.setLine(I1left); :}
              ;
AbstractClassName ::= (AbstractClassNameNoExtends) IDENT:I1 {: RESULT=new AbstractClassNameNoExtends(I1); RESULT.setLine(I1left); :}
                      |
                      (AbstractClassNameExtends) IDENT:I1 EXTENDS Type:T2 {: RESULT=new AbstractClassNameExtends(I1, T2); RESULT.setLine(I1left); :}
                      ;
FieldDeclarationList ::= (FieldDeclarationListMore) FieldDeclarationList:F1 FieldDeclaration:F2 {: RESULT=new FieldDeclarationListMore(F1, F2); RESULT.setLine(F1left); :}
                         |
                         (FieldDeclarationListEmpty) {: RESULT=new FieldDeclarationListEmpty(); :} /* epsilon */
                         ;
FieldDeclaration ::= (FieldDeclaration) Type:T1 FieldList:F2 SEMI {: RESULT=new FieldDeclaration(T1, F2); RESULT.setLine(T1left); :};
FieldList ::= (FieldListMultiple) FieldList:F1 COMMA Field:F2 {: RESULT=new FieldListMultiple(F1, F2); RESULT.setLine(F1left); :}
            |
            (FieldListSingle) Field:F1 {: RESULT=new FieldListSingle(F1); RESULT.setLine(F1left); :}
            ;
Field ::= (FieldSingle) IDENT:I1 {: RESULT=new FieldSingle(I1); RESULT.setLine(I1left); :}
        |
        (FieldArray) IDENT:I1 LBRACKET RBRACKET {: RESULT=new FieldArray(I1); RESULT.setLine(I1left); :}
        ;
VarDeclarationList ::= (VarDeclarationListMore) VarDeclarationList:V1 VarDeclaration:V2 {: RESULT=new VarDeclarationListMore(V1, V2); RESULT.setLine(V1left); :}
                       |
                       (VarDeclarationListEmpty) {: RESULT=new VarDeclarationListEmpty(); :} /* epsilon */
                       ;
VarDeclaration ::= (VarDeclaration) Type:T1 VarList:V2 SEMI {: RESULT=new VarDeclaration(T1, V2); RESULT.setLine(T1left); :};
VarList ::= (VarListMultiple) VarList:V1 COMMA Var:V2 {: RESULT=new VarListMultiple(V1, V2); RESULT.setLine(V1left); :}
            |
            (VarListSingle) Var:V1 {: RESULT=new VarListSingle(V1); RESULT.setLine(V1left); :}
            ;
Var ::= (VarSingle) IDENT:I1 {: RESULT=new VarSingle(I1); RESULT.setLine(I1left); :}
        |
        (VarArray) IDENT:I1 LBRACKET RBRACKET {: RESULT=new VarArray(I1); RESULT.setLine(I1left); :}
        ;
MethodDeclarationList ::= (MethodDeclarationListMore) MethodDeclarationList:M1 MethodDeclaration:M2 {: RESULT=new MethodDeclarationListMore(M1, M2); RESULT.setLine(M1left); :}
                          |
                          (MethodDeclarationListEmpty) {: RESULT=new MethodDeclarationListEmpty(); :} /* epsilon */
                          ;
AbstractClassMethodDeclarationList ::= (AbstractClassMethodDeclarationListAbstract) AbstractClassMethodDeclarationList:A1 AbstractMethodDeclaration:A2 {: RESULT=new AbstractClassMethodDeclarationListAbstract(A1, A2); RESULT.setLine(A1left); :}
                                       |
                                       (AbstractClassMethodDeclarationListConcrete) AbstractClassMethodDeclarationList:A1 MethodDeclaration:M2 {: RESULT=new AbstractClassMethodDeclarationListConcrete(A1, M2); RESULT.setLine(A1left); :}
                                       |
                                       (AbstractClassMethodDeclarationListEmpty) {: RESULT=new AbstractClassMethodDeclarationListEmpty(); :} /* epsilon */
                                       ;
MethodDeclaration ::= (MethodDeclarationParams) MethodHeader:M1 LPAREN FormalParamsList:F2 RPAREN VarDeclarationList:V3 LBRACE StatementList:S4 RBRACE {: RESULT=new MethodDeclarationParams(M1, F2, V3, S4); RESULT.setLine(M1left); :}
                      |
                      (MethodDeclarationNoParams) MethodHeader:M1 LPAREN RPAREN VarDeclarationList:V2 LBRACE StatementList:S3 RBRACE {: RESULT=new MethodDeclarationNoParams(M1, V2, S3); RESULT.setLine(M1left); :}
                      ;
AbstractMethodDeclaration ::= (AbstractMethodDeclarationParams) ABSTRACT MethodHeader:M1 LPAREN FormalParamsList:F2 RPAREN SEMI {: RESULT=new AbstractMethodDeclarationParams(M1, F2); RESULT.setLine(M1left); :}
                              |
                              (AbstractMethodDeclarationNoParams) ABSTRACT MethodHeader:M1 LPAREN RPAREN SEMI {: RESULT=new AbstractMethodDeclarationNoParams(M1); RESULT.setLine(M1left); :}
                              ;
MethodHeader ::= (MethodHeaderType) Type:T1 IDENT:I2 {: RESULT=new MethodHeaderType(T1, I2); RESULT.setLine(T1left); :}
                 |
                 (MethodHeaderVoid) VOID IDENT:I1 {: RESULT=new MethodHeaderVoid(I1); RESULT.setLine(I1left); :}
                 ;
FormalParamsList ::= (FormalParamsListMultiple) FormalParamsList:F1 COMMA FormalParam:F2 {: RESULT=new FormalParamsListMultiple(F1, F2); RESULT.setLine(F1left); :}
                     |
                     (FormalParamsListSingle) FormalParam:F1 {: RESULT=new FormalParamsListSingle(F1); RESULT.setLine(F1left); :}
                     ;
FormalParam ::= (FormalParamSingle) Type:T1 IDENT:I2 {: RESULT=new FormalParamSingle(T1, I2); RESULT.setLine(T1left); :}
                |
                (FormalParamArray) Type:T1 IDENT:I2 LBRACKET RBRACKET {: RESULT=new FormalParamArray(T1, I2); RESULT.setLine(T1left); :}
                ;
StatementList ::= (StatementListMore) StatementList:S1 Statement:S2 {: RESULT=new StatementListMore(S1, S2); RESULT.setLine(S1left); :}
                  |
                  (StatementListEmpty) {: RESULT=new StatementListEmpty(); :} /* epsilon */
                  ;
Statement ::= (StatementDesignator) DesignatorStatement:D1 SEMI {: RESULT=new StatementDesignator(D1); RESULT.setLine(D1left); :}
              |
              (StatementIf) IF LPAREN Condition:C1 RPAREN Statement:S2 Else:E3 {: RESULT=new StatementIf(C1, S2, E3); RESULT.setLine(C1left); :}
              |
              (StatementBreak) BREAK SEMI {: RESULT=new StatementBreak(); :}
              |
              (StatementContinue) CONTINUE SEMI {: RESULT=new StatementContinue(); :}
              |
              (StatementReturnNoExpression) Return:R1 SEMI {: RESULT=new StatementReturnNoExpression(R1); RESULT.setLine(R1left); :}
              |
              (StatementReturnExpression) Return:R1 Expression:E2 SEMI {: RESULT=new StatementReturnExpression(R1, E2); RESULT.setLine(R1left); :}
              |
              (StatementRead) READ LPAREN Designator:D1 RPAREN SEMI {: RESULT=new StatementRead(D1); RESULT.setLine(D1left); :}
              |
              (StatementPrintNoNumConst) PRINT LPAREN Expression:E1 RPAREN SEMI {: RESULT=new StatementPrintNoNumConst(E1); RESULT.setLine(E1left); :}
              |
              (StatementPrintNumConst) PRINT LPAREN Expression:E1 COMMA NUM_CONST:N2 RPAREN SEMI {: RESULT=new StatementPrintNumConst(E1, N2); RESULT.setLine(E1left); :}
              |
              (StatementSwitch) SwitchStart:S1 LPAREN Expression:E2 RPAREN LBRACE CaseList:C3 RBRACE {: RESULT=new StatementSwitch(S1, E2, C3); RESULT.setLine(S1left); :}
              |
              (StatementFor) ForStart:F1 LPAREN ForInit:F2 SEMI ForCond:F3 SEMI ForAct:F4 RPAREN Statement:S5 {: RESULT=new StatementFor(F1, F2, F3, F4, S5); RESULT.setLine(F1left); :}
              |
              (StatementBlock) LBRACE StatementList:S1 RBRACE {: RESULT=new StatementBlock(S1); RESULT.setLine(S1left); :}
              ;
Return ::= (Return) RETURN {: RESULT=new Return(); :};
Else ::= (ElseNotEmpty) SkipElse:S1 Statement:S2 {: RESULT=new ElseNotEmpty(S1, S2); RESULT.setLine(S1left); :}
         |
         (ElseEmpty) {: RESULT=new ElseEmpty(); :} /* epsilon */
         ;
SkipElse ::= (SkipElse) ELSE {: RESULT=new SkipElse(); :};
SkipTernary ::= (SkipTernary) COLON {: RESULT=new SkipTernary(); :};
ForStart ::= (ForStart) FOR {: RESULT=new ForStart(); :};
ForInit ::= (ForInitNotEmpty) DesignatorStatement:D1 {: RESULT=new ForInitNotEmpty(D1); RESULT.setLine(D1left); :}
            |
            (ForInitEmpty) {: RESULT=new ForInitEmpty(); :} /* epsilon */
            ;
ForCond ::= (ForCondNotEmpty) Condition:C1 {: RESULT=new ForCondNotEmpty(C1); RESULT.setLine(C1left); :}
            |
            (ForCondEmpty) {: RESULT=new ForCondEmpty(); :} /* epsilon */
            ;
ForAct ::= (ForActNotEmpty) DesignatorStatement:D1 {: RESULT=new ForActNotEmpty(D1); RESULT.setLine(D1left); :}
           |
           (ForActEmpty) {: RESULT=new ForActEmpty(); :} /* epsilon */
           ;
SwitchStart ::= (SwitchStart) SWITCH {: RESULT=new SwitchStart(); :};
CaseList ::= (CaseListMore) CaseList:C1 Case:C2 {: RESULT=new CaseListMore(C1, C2); RESULT.setLine(C1left); :}
             |
             (CaseListEmpty) {: RESULT=new CaseListEmpty(); :} /* epsilon */
             ;
CaseStart ::= (CaseStart) CASE NUM_CONST:N1 {: RESULT=new CaseStart(N1); RESULT.setLine(N1left); :};
Case ::= (Case) CaseStart:C1 COLON StatementList:S2 {: RESULT=new Case(C1, S2); RESULT.setLine(C1left); :};
DesignatorStatement ::= (DesignatorStatementAssign) Designator:D1 ASSIGN Expression:E2 {: RESULT=new DesignatorStatementAssign(D1, E2); RESULT.setLine(D1left); :}
                        |
                        (DesignatorStatementFunctionCallParams) Designator:D1 LPAREN ActualParamsList:A2 RPAREN {: RESULT=new DesignatorStatementFunctionCallParams(D1, A2); RESULT.setLine(D1left); :}
                        |
                        (DesignatorStatementFunctionCallNoParams) Designator:D1 LPAREN RPAREN {: RESULT=new DesignatorStatementFunctionCallNoParams(D1); RESULT.setLine(D1left); :}
                        |
                        (DesignatorStatementIncrement) Designator:D1 INC {: RESULT=new DesignatorStatementIncrement(D1); RESULT.setLine(D1left); :}
                        |
                        (DesignatorStatementDecrement) Designator:D1 DEC {: RESULT=new DesignatorStatementDecrement(D1); RESULT.setLine(D1left); :}
                        ;
ActualParamsList ::= (ActualParamsListMultiple) ActualParamsList:A1 COMMA Expression:E2 {: RESULT=new ActualParamsListMultiple(A1, E2); RESULT.setLine(A1left); :}
                     |
                     (ActualParamsListSingle) Expression:E1 {: RESULT=new ActualParamsListSingle(E1); RESULT.setLine(E1left); :}
                     ;
Designator ::= (DesignatorFieldVar) Designator:D1 DOT IDENT:I2 {: RESULT=new DesignatorFieldVar(D1, I2); RESULT.setLine(D1left); :}
               |
               (DesignatorFieldArray) FieldArrayName:F1 LBRACKET Expression:E2 RBRACKET {: RESULT=new DesignatorFieldArray(F1, E2); RESULT.setLine(F1left); :}
               |
               (DesignatorLength) Designator:D1 DOT LENGTH {: RESULT=new DesignatorLength(D1); RESULT.setLine(D1left); :}
               |
               (DesignatorEndVar) IDENT:I1 {: RESULT=new DesignatorEndVar(I1); RESULT.setLine(I1left); :}
               |
               (DesignatorEndArray) EndArrayName:E1 LBRACKET Expression:E2 RBRACKET {: RESULT=new DesignatorEndArray(E1, E2); RESULT.setLine(E1left); :}
               ;
EndArrayName ::= (EndArrayName) IDENT:I1 {: RESULT=new EndArrayName(I1); RESULT.setLine(I1left); :};
FieldArrayName ::= (FieldArrayName) Designator:D1 DOT IDENT:I2 {: RESULT=new FieldArrayName(D1, I2); RESULT.setLine(D1left); :};
Expression ::= (ExpressionArithmetic) ArithmeticExpression:A1 {: RESULT=new ExpressionArithmetic(A1); RESULT.setLine(A1left); :}
               |
               (ExpressionTernary) Condition:C1 QUESTION Expression:E2 SkipTernary:S3 Expression:E4 {: RESULT=new ExpressionTernary(C1, E2, S3, E4); RESULT.setLine(C1left); :}
               ;
ArithmeticExpression ::= (ArithmeticExpression) TermList:T1 {: RESULT=new ArithmeticExpression(T1); RESULT.setLine(T1left); :};
TermList ::= (TermListAddOp) TermList:T1 AddOp:A2 Term:T3 {: RESULT=new TermListAddOp(T1, A2, T3); RESULT.setLine(T1left); :}
             |
             (TermListNoAddOp) Term:T1 {: RESULT=new TermListNoAddOp(T1); RESULT.setLine(T1left); :}
             ;
Term ::= (Term) FactorList:F1 {: RESULT=new Term(F1); RESULT.setLine(F1left); :};
FactorList ::= (FactorListMulOp) FactorList:F1 MulOp:M2 Factor:F3 {: RESULT=new FactorListMulOp(F1, M2, F3); RESULT.setLine(F1left); :}
               |
               (FactorListNoMulOp) Factor:F1 {: RESULT=new FactorListNoMulOp(F1); RESULT.setLine(F1left); :}
               ;
Factor ::= (FactorVariable) Sign:S1 Designator:D2 {: RESULT=new FactorVariable(S1, D2); RESULT.setLine(S1left); :}
           |
           (FactorFunctionCallWithArgs) Sign:S1 Designator:D2 LPAREN ActualParamsList:A3 RPAREN {: RESULT=new FactorFunctionCallWithArgs(S1, D2, A3); RESULT.setLine(S1left); :}
           |
           (FactorFunctionCallNoArgs) Sign:S1 Designator:D2 LPAREN RPAREN {: RESULT=new FactorFunctionCallNoArgs(S1, D2); RESULT.setLine(S1left); :}
           |
           (FactorNumConst) Sign:S1 NUM_CONST:N2 {: RESULT=new FactorNumConst(S1, N2); RESULT.setLine(S1left); :}
           |
           (FactorBoolConst) BOOL_CONST:B1 {: RESULT=new FactorBoolConst(B1); RESULT.setLine(B1left); :}
           |
           (FactorCharConst) CHAR_CONST:C1 {: RESULT=new FactorCharConst(C1); RESULT.setLine(C1left); :}
           |
           (FactorNewVar) NEW Type:T1 {: RESULT=new FactorNewVar(T1); RESULT.setLine(T1left); :}
           |
           (FactorNewArray) NEW Type:T1 LBRACKET Expression:E2 RBRACKET {: RESULT=new FactorNewArray(T1, E2); RESULT.setLine(T1left); :}
           |
           (FactorNested) Sign:S1 LPAREN Expression:E2 RPAREN {: RESULT=new FactorNested(S1, E2); RESULT.setLine(S1left); :}
           ;
Sign ::= (SignMinus) MINUS {: RESULT=new SignMinus(); :}
         |
         (SignEmpty) {: RESULT=new SignEmpty(); :} /* epsilon */
         ;
Condition ::= (ConditionMultiple) Condition:C1 OR ConditionTerm:C2 {: RESULT=new ConditionMultiple(C1, C2); RESULT.setLine(C1left); :}
              |
              (ConditionSingle) ConditionTerm:C1 {: RESULT=new ConditionSingle(C1); RESULT.setLine(C1left); :}
              ;
ConditionTerm ::= (ConditionTermMultiple) ConditionTerm:C1 AND ConditionFactor:C2 {: RESULT=new ConditionTermMultiple(C1, C2); RESULT.setLine(C1left); :}
                  |
                  (ConditionTermSingle) ConditionFactor:C1 {: RESULT=new ConditionTermSingle(C1); RESULT.setLine(C1left); :}
                  ;
ConditionFactor ::= (ConditionFactorNoRelOp) ArithmeticExpression:A1 {: RESULT=new ConditionFactorNoRelOp(A1); RESULT.setLine(A1left); :}
                    |
                    (ConditionFactorRelOp) ArithmeticExpression:A1 RelOp:R2 ArithmeticExpression:A3 {: RESULT=new ConditionFactorRelOp(A1, R2, A3); RESULT.setLine(A1left); :}
                    ;
RelOp ::= (RelOpEqual) EQUAL {: RESULT=new RelOpEqual(); :}
          |
          (RelOpNotEqual) NOT_EQUAL {: RESULT=new RelOpNotEqual(); :}
          |
          (RelOpGreater) GREATER {: RESULT=new RelOpGreater(); :}
          |
          (RelOpGreaterEqual) GREATER_EQUAL {: RESULT=new RelOpGreaterEqual(); :}
          |
          (RelOpLess) LESS {: RESULT=new RelOpLess(); :}
          |
          (RelOpLessEqual) LESS_EQUAL {: RESULT=new RelOpLessEqual(); :}
          ;
AddOp ::= (AddOpPlus) PLUS {: RESULT=new AddOpPlus(); :}
          |
          (AddOpMinus) MINUS {: RESULT=new AddOpMinus(); :}
          ;
MulOp ::= (MulOpTimes) MUL {: RESULT=new MulOpTimes(); :}
          |
          (MulOpDiv) DIV {: RESULT=new MulOpDiv(); :}
          |
          (MulOpMod) MOD {: RESULT=new MulOpMod(); :}
          ;