package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:
    boolean errorDetected = false;
    Logger log = Logger.getLogger(getClass());

    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
        done_parsing();
        report_error(message, info);
    }

    public void syntax_error(Symbol curr_token) {
        report_error("\nSintaksna greska", curr_token);
    }

    public void unrecovered_syntax_error(Symbol curr_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", curr_token);
    }

    public void report_error(String message, Object info) {
        errorDetected = true;
        StringBuilder msg = new StringBuilder(message);
        if (info instanceof Symbol) {
            msg.append(" na liniji ").append(((Symbol)info).left);
        }
        log.error(msg.toString());
    }
:}

scan with {:
    Symbol s = this.getScanner().next_token();
    if (s != null && s.value != null) {
        log.info(s.toString() + " " + s.value.toString());
    }
    return s;
:}

terminal PROGRAM, ENUM, CLASS, ABSTRACT, CONST, VOID, EXTENDS;
terminal BREAK, ELSE, IF, NEW, PRINT, READ, RETURN, CONTINUE, FOR, LENGTH, SWITCH, CASE;
terminal PLUS, MINUS, MUL, DIV, MOD, AND, OR, ASSIGN, INC, DEC;
terminal EQUAL, NOT_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL;
terminal SEMI, COLON, COMMA, DOT, LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, QUESTION;
terminal String IDENT;
terminal Integer NUM_CONST;
terminal Character CHAR_CONST;
terminal Boolean BOOL_CONST;

nonterminal Program, DeclarationList, GlobalVarDeclaration, GlobalVarList, GlobalVar;
nonterminal GlobalMethodDeclarationList, GlobalMethodDeclaration;
nonterminal ConstDeclaration, VarDeclaration, ClassDeclaration, EnumDeclaration, AbstractClassDeclaration;
nonterminal Type, ConstList, Const, VarList, Var, EnumConstList, EnumConst;
nonterminal MethodDeclarationList, AbstractClassMethodDeclarationList, VarDeclarationList;
nonterminal MethodDeclaration, AbstractMethodDeclaration, FormalParamsList, FormalParam;
nonterminal StatementList, Statement, DesignatorStatement, CaseList, Case;
nonterminal IfDeclaration, ReturnDeclaration, PrintDeclaration, ForDeclaration;
nonterminal Condition, ActualParamsList, ConditionFactor, ConditionTerm, Sign;
nonterminal ProgramName, EnumName, ClassName, AbstractClassName, RelOp, AddOp, MulOp;
nonterminal FieldDeclarationList, FieldDeclaration, FieldList, Field, ForStart, CaseStart, SwitchStart;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Term, TermList, Factor, FactorList, ArithmeticExpression, Expression;
nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, MethodHeader, GlobalMethodHeader;

precedence left ELSE;

Program ::= (Program) PROGRAM ProgramName DeclarationList LBRACE GlobalMethodDeclarationList RBRACE;
ProgramName ::= (ProgramName) IDENT;
DeclarationList ::= (DeclarationListConst) DeclarationList ConstDeclaration
                    |
                    (DeclarationListVar) DeclarationList GlobalVarDeclaration
                    |
                    (DeclarationListClass) DeclarationList ClassDeclaration
                    |
                    (DeclarationListEnum) DeclarationList EnumDeclaration
                    |
                    (DeclarationListAbstractClass) DeclarationList AbstractClassDeclaration
                    |
                    (DeclarationListEmpty) /* epsilon */
                    ;
ConstDeclaration ::= (ConstDeclaration) CONST Type ConstList SEMI;
Type ::= (Type) IDENT;
ConstList ::= (ConstListMultiple) ConstList COMMA Const
              |
              (ConstListSingle) Const
              ;
Const ::= (ConstNum) IDENT ASSIGN NUM_CONST
          |
          (ConstChar) IDENT ASSIGN CHAR_CONST
          |
          (ConstBool) IDENT ASSIGN BOOL_CONST
          ;
GlobalVarDeclaration ::= (GlobalVarDeclaration) Type GlobalVarList SEMI;
GlobalVarList ::= (GlobalVarListMultiple) GlobalVarList COMMA GlobalVar
                  |
                  (GlobalVarListSingle) GlobalVar
                  ;
GlobalVar ::= (GlobalVarSingle) IDENT
              |
              (GlobalVarArray) IDENT LBRACKET RBRACKET
              ;
GlobalMethodDeclarationList ::= (GlobalMethodDeclarationListMore) GlobalMethodDeclarationList GlobalMethodDeclaration
                                |
                                (GlobalMethodDeclarationListEmpty) /* epsilon */
                                ;
GlobalMethodDeclaration ::= (GlobalMethodDeclarationParams) GlobalMethodHeader LPAREN FormalParamsList RPAREN VarDeclarationList LBRACE StatementList RBRACE
                            |
                            (GlobalMethodDeclarationNoParams) GlobalMethodHeader LPAREN RPAREN VarDeclarationList LBRACE StatementList RBRACE
                            ;
GlobalMethodHeader ::= (GlobalMethodHeaderType) Type IDENT
                       |
                       (GlobalMethodHeaderVoid) VOID IDENT
                       ;
EnumDeclaration ::= (EnumDeclaration) ENUM EnumName LBRACE EnumConstList RBRACE;
EnumName ::= (EnumName) IDENT;
EnumConstList ::= (EnumConstListMultiple) EnumConstList COMMA EnumConst
                  |
                  (EnumConstListSingle) EnumConst
                  ;
EnumConst ::= (EnumConstNoAssign) IDENT
              |
              (EnumConstAssign) IDENT ASSIGN NUM_CONST
              ;
ClassDeclaration ::= (ClassDeclarationMethodList) CLASS ClassName LBRACE FieldDeclarationList LBRACE MethodDeclarationList RBRACE RBRACE
                     |
                     (ClassDeclarationNoMethodList) CLASS ClassName LBRACE FieldDeclarationList RBRACE
                     ;
AbstractClassDeclaration ::= (AbstractClassDeclarationMethodList) ABSTRACT CLASS AbstractClassName LBRACE FieldDeclarationList LBRACE AbstractClassMethodDeclarationList RBRACE RBRACE
                             |
                             (AbstractClassDeclarationNoMethodList) ABSTRACT CLASS AbstractClassName LBRACE FieldDeclarationList RBRACE
                             ;
ClassName ::= (ClassNameNoExtends) IDENT
              |
              (ClassNameExtends) IDENT EXTENDS Type
              ;
AbstractClassName ::= (AbstractClassNameNoExtends) IDENT
                      |
                      (AbstractClassNameExtends) IDENT EXTENDS Type
                      ;
FieldDeclarationList ::= (FieldDeclarationListMore) FieldDeclarationList FieldDeclaration
                         |
                         (FieldDeclarationListEmpty) /* epsilon */
                         ;
FieldDeclaration ::= (FieldDeclaration) Type FieldList SEMI;
FieldList ::= (FieldListMultiple) FieldList COMMA Field
            |
            (FieldListSingle) Field
            ;
Field ::= (FieldSingle) IDENT
        |
        (FieldArray) IDENT LBRACKET RBRACKET
        ;
VarDeclarationList ::= (VarDeclarationListMore) VarDeclarationList VarDeclaration
                       |
                       (VarDeclarationListEmpty) /* epsilon */
                       ;
VarDeclaration ::= (VarDeclaration) Type VarList SEMI;
VarList ::= (VarListMultiple) VarList COMMA Var
            |
            (VarListSingle) Var
            ;
Var ::= (VarSingle) IDENT
        |
        (VarArray) IDENT LBRACKET RBRACKET
        ;
MethodDeclarationList ::= (MethodDeclarationListMore) MethodDeclarationList MethodDeclaration
                          |
                          (MethodDeclarationListEmpty) /* epsilon */
                          ;
AbstractClassMethodDeclarationList ::= (AbstractClassMethodDeclarationListAbstract) AbstractClassMethodDeclarationList AbstractMethodDeclaration
                                       |
                                       (AbstractClassMethodDeclarationListConcrete) AbstractClassMethodDeclarationList MethodDeclaration
                                       |
                                       (AbstractClassMethodDeclarationListEmpty) /* epsilon */
                                       ;
MethodDeclaration ::= (MethodDeclarationParams) MethodHeader LPAREN FormalParamsList RPAREN VarDeclarationList LBRACE StatementList RBRACE
                      |
                      (MethodDeclarationNoParams) MethodHeader LPAREN RPAREN VarDeclarationList LBRACE StatementList RBRACE
                      ;
AbstractMethodDeclaration ::= (AbstractMethodDeclarationParams) ABSTRACT MethodHeader LPAREN FormalParamsList RPAREN SEMI
                              |
                              (AbstractMethodDeclarationNoParams) ABSTRACT MethodHeader LPAREN RPAREN SEMI
                              ;
MethodHeader ::= (MethodHeaderType) Type IDENT
                 |
                 (MethodHeaderVoid) VOID IDENT
                 ;
FormalParamsList ::= (FormalParamsListMultiple) FormalParamsList COMMA FormalParam
                     |
                     (FormalParamsListSingle) FormalParam
                     ;
FormalParam ::= (FormalParamSingle) Type IDENT
                |
                (FormalParamArray) Type IDENT LBRACKET RBRACKET
                ;
StatementList ::= (StatementListMore) StatementList Statement
                  |
                  (StatementListEmpty) /* epsilon */
                  ;
Statement ::= (StatementDesignator) DesignatorStatement SEMI
              |
              (StatementIf) IF LPAREN Condition RPAREN Statement IfDeclaration
              |
              (StatementBreak) BREAK SEMI
              |
              (StatementContinue) CONTINUE SEMI
              |
              (StatementReturn) RETURN ReturnDeclaration SEMI
              |
              (StatementRead) READ LPAREN Designator RPAREN SEMI
              |
              (StatementPrint) PRINT LPAREN Expression PrintDeclaration RPAREN SEMI
              |
              (StatementSwitch) SwitchStart LPAREN Expression RPAREN LBRACE CaseList RBRACE
              |
              (StatementFor) ForStart LPAREN ForDeclaration RPAREN Statement
              |
              (StatementBlock) LBRACE StatementList RBRACE
              ;
IfDeclaration ::= (IfDeclarationElse) ELSE Statement
                  |
                  (IfDeclarationNoElse) /* epsilon */
                  ;
ReturnDeclaration ::= (ReturnDeclarationExpression) Expression
                      |
                      (ReturnDeclarationNoExpression) /* epsilon */
                      ;
PrintDeclaration ::= (PrintDeclarationNumConst) COMMA NUM_CONST
                     |
                     (PrintDeclarationNoNumConst) /* epsilon */
                     ;
ForStart ::= (ForStart) FOR;
ForDeclaration ::= (ForDeclarationFull) DesignatorStatement SEMI Condition SEMI DesignatorStatement
                   |
                   (ForDeclarationNoInit) SEMI Condition SEMI DesignatorStatement
                   |
                   (ForDeclarationNoCond) DesignatorStatement SEMI SEMI DesignatorStatement
                   |
                   (ForDeclarationNoAct) DesignatorStatement SEMI Condition SEMI
                   |
                   (ForDeclarationNoInitNoCond) SEMI SEMI DesignatorStatement
                   |
                   (ForDeclarationNoInitNoAct) SEMI Condition SEMI
                   |
                   (ForDeclarationNoCondNoAct) DesignatorStatement SEMI SEMI
                   |
                   (ForDeclarationNoInitNoCondNoAct) SEMI SEMI
                   ;
SwitchStart ::= (SwitchStart) SWITCH;
CaseList ::= (CaseListMore) CaseList Case
             |
             (CaseListEmpty) /* epsilon */
             ;
CaseStart ::= (CaseStart) CASE;
Case ::= (Case) CaseStart NUM_CONST COLON StatementList;
DesignatorStatement ::= (DesignatorStatementAssign) Designator ASSIGN Expression
                        |
                        (DesignatorStatementFunctionCallParams) Designator LPAREN ActualParamsList RPAREN
                        |
                        (DesignatorStatementFunctionCallNoParams) Designator LPAREN RPAREN
                        |
                        (DesignatorStatementIncrement) Designator INC
                        |
                        (DesignatorStatementDecrement) Designator DEC
                        ;
ActualParamsList ::= (ActualParamsListMultiple) ActualParamsList COMMA Expression
                     |
                     (ActualParamsListSingle) Expression
                     ;
Designator ::= (DesignatorFieldVar) Designator DOT IDENT
               |
               (DesignatorFieldArray) Designator DOT IDENT LBRACKET Expression RBRACKET
               |
               (DesignatorLength) Designator DOT LENGTH
               |
               (DesignatorEndVar) IDENT
               |
               (DesignatorEndArray) IDENT LBRACKET Expression RBRACKET
               ;
Expression ::= (ExpressionArithmetic) ArithmeticExpression
               |
               (ExpressionTernary) Condition QUESTION Expression COLON Expression
               ;
ArithmeticExpression ::= (ArithmeticExpression) TermList;
TermList ::= (TermListAddOp) TermList AddOp Term
             |
             (TermListNoAddOp) Term
             ;
Term ::= (Term) FactorList;
FactorList ::= (FactorListMulOp) FactorList MulOp Factor
               |
               (FactorListNoMulOp) Factor
               ;
Factor ::= (FactorVariable) Sign Designator
           |
           (FactorFunctionCallWithArgs) Sign Designator LPAREN ActualParamsList RPAREN
           |
           (FactorFunctionCallNoArgs) Sign Designator LPAREN RPAREN
           |
           (FactorNumConst) Sign NUM_CONST
           |
           (FactorBoolConst) BOOL_CONST
           |
           (FactorCharConst) CHAR_CONST
           |
           (FactorNewVar) NEW Type
           |
           (FactorNewArray) NEW Type LBRACKET Expression RBRACKET
           |
           (FactorNested) Sign LPAREN Expression RPAREN
           ;
Sign ::= (SignMinus) MINUS
         |
         (SignEmpty) /* epsilon */
         ;
Condition ::= (ConditionMultiple) Condition OR ConditionTerm
              |
              (ConditionSingle) ConditionTerm
              ;
ConditionTerm ::= (ConditionTermMultiple) ConditionTerm AND ConditionFactor
                  |
                  (ConditionTermSingle) ConditionFactor
                  ;
ConditionFactor ::= (ConditionFactorNoRelOp) ArithmeticExpression
                    |
                    (ConditionFactorRelOp) ArithmeticExpression RelOp ArithmeticExpression
                    ;
RelOp ::= (RelOpEqual) EQUAL
          |
          (RelOpNotEqual) NOT_EQUAL
          |
          (RelOpGreater) GREATER
          |
          (RelOpGreaterEqual) GREATER_EQUAL
          |
          (RelOpLess) LESS
          |
          (RelOpLessEqual) LESS_EQUAL
          ;
AddOp ::= (AddOpPlus) PLUS
          |
          (AddOpMinus) MINUS
          ;
MulOp ::= (MulOpTimes) MUL
          |
          (MulOpDiv) DIV
          |
          (MulOpMod) MOD
          ;